# yaml-language-server: $schema=https://raw.githubusercontent.com/loozhengyuan/blt/main/schema/v1/schema.json
version: 1
kind: dnsbl
policy:
  deny:
    items:
      # Hikvision
      - dev.ys7.com
      - litedev.ys7.com
      - dev1.sq.ys7.com
      - dev2.xy.ys7.com
    includes:
      - name: Adguard DNS Filter
        url: https://v.firebog.net/hosts/AdguardDNS.txt
      - name: EasyList
        url: https://v.firebog.net/hosts/Easylist.txt
      - name: Admiral List
        url: https://v.firebog.net/hosts/Admiral.txt
      # - name: OISD Basic List
      #   url: https://dbl.oisd.nl/basic/
output:
  destinations:
    - filePath: dist/hosts/hosts
      customTemplate: |
        # DNS Blocklist
        # 
        # Last updated at {{ .LastUpdated }}

        {{ range .Items -}}
        127.0.0.1   {{ . }}
        ::1         {{ . }}
        {{ end -}}
